/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication12;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author rohit
 */
public class Fill_marks extends javax.swing.JFrame {

    /**
     * Creates new form enter_marks
     */
    public Fill_marks() {
        initComponents();
    }
    public Fill_marks(String reg_no,int current_sem)
    {
        initComponents();
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");
            jLabel7.setText(reg_no);
            jLabel8.setText(""+current_sem);
            String sql;
            sql="SELECT Department,acadmic_year FROM rps.student_info WHERE reg_no='"+reg_no+"';";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            rs.next();
            String department=rs.getString("Department");
            String acadmic_year=rs.getString("acadmic_year");
            sql="SELECT * FROM subject WHERE sem='"+current_sem+"' AND department='"+department+"' AND acadmic_year='"+acadmic_year+"';";
            rs=pst.executeQuery(sql);
            
            JLabel[] jlabels={sub1,sub2,sub3,sub4,sub5,sub6,sub7,sub8};
            JTextField[] thmarks={jt1,jt2,jt3,jt4,jt5,jt6,jt7,jt8};
            JTextField[] prmarks={jp1,jp2,jp3,jp4,jp5,jp6,jp7,jp8};
            JTextField[] midmarks={jm1,jm2,jm3,jm4,jm5,jm6,jm7,jm8};
            int i=0;
            while(rs.next())
            {
                int credit_th=rs.getInt("credit_th");
                int credit_pr=rs.getInt("credit_pr");
                
                if(credit_th==0)
                {
                    thmarks[i].setEditable(false);
                    thmarks[i].setText("0");
                
                }
                    
                else if(credit_pr==0)
                {
                    prmarks[i].setEditable(false);
                    prmarks[i].setText("0");
                }
                 
                jlabels[i].setText(rs.getString("sub_name"));
                i=i+1;
            }
            
            for(;i<8;i++)
            {
                jlabels[i].setVisible(false);
                thmarks[i].setVisible(false);
                prmarks[i].setVisible(false);
                midmarks[i].setVisible(false);
            }
            rs.close();
            pst.close();
            conn.close();
            
            
            
        } catch (ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sub1 = new javax.swing.JLabel();
        jm1 = new javax.swing.JTextField();
        jt1 = new javax.swing.JTextField();
        jp1 = new javax.swing.JTextField();
        sub2 = new javax.swing.JLabel();
        jm2 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jp2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JLabel();
        jm3 = new javax.swing.JTextField();
        jt3 = new javax.swing.JTextField();
        jp3 = new javax.swing.JTextField();
        sub4 = new javax.swing.JLabel();
        jm4 = new javax.swing.JTextField();
        jt4 = new javax.swing.JTextField();
        jp4 = new javax.swing.JTextField();
        jp5 = new javax.swing.JTextField();
        jt5 = new javax.swing.JTextField();
        jm5 = new javax.swing.JTextField();
        sub5 = new javax.swing.JLabel();
        jm6 = new javax.swing.JTextField();
        jt6 = new javax.swing.JTextField();
        jp6 = new javax.swing.JTextField();
        sub6 = new javax.swing.JLabel();
        sub7 = new javax.swing.JLabel();
        sub8 = new javax.swing.JLabel();
        jm7 = new javax.swing.JTextField();
        jt7 = new javax.swing.JTextField();
        jp7 = new javax.swing.JTextField();
        jm8 = new javax.swing.JTextField();
        jt8 = new javax.swing.JTextField();
        jp8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Enrollment Number");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Sem");

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        sub1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub1.setText("-");

        jm1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm1ActionPerformed(evt);
            }
        });

        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });

        sub2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub2.setText("-");

        jm2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm2ActionPerformed(evt);
            }
        });

        jt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt2ActionPerformed(evt);
            }
        });

        sub3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub3.setText("-");

        jm3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt3ActionPerformed(evt);
            }
        });

        sub4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub4.setText("-");

        jm4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt4ActionPerformed(evt);
            }
        });

        jm5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sub5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub5.setText("-");

        jm6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt6ActionPerformed(evt);
            }
        });

        sub6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub6.setText("-");

        sub7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub7.setText("-");

        sub8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sub8.setText("-");

        jm7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jt7.setName(""); // NOI18N
        jt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt7ActionPerformed(evt);
            }
        });

        jm8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sub7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(sub5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sub8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jm5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jm7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jm1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jm8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sub1.getAccessibleContext().setAccessibleName("subject1");
        sub2.getAccessibleContext().setAccessibleName("subject2");
        sub3.getAccessibleContext().setAccessibleName("subject3");
        sub4.getAccessibleContext().setAccessibleName("subject4");
        sub5.getAccessibleContext().setAccessibleName("subject5");
        sub6.getAccessibleContext().setAccessibleName("subject6");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("MT");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PR");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("TH");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Roll Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("--");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel5)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton3)
                                .addGap(158, 158, 158)
                                .addComponent(jButton4)
                                .addGap(150, 150, 150)
                                .addComponent(jButton2)))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        jLabel7.getAccessibleContext().setAccessibleName("enroll_no");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Mainframe m=new Mainframe();
m.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1ActionPerformed

    private void jt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt2ActionPerformed

    private void jt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt4ActionPerformed

    private void jt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt6ActionPerformed

    private void jt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt3ActionPerformed

    private void jt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt7ActionPerformed

    private void jt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt8ActionPerformed

    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");      
            
            String reg_no=jLabel7.getText();
            int roll_no=Integer.parseInt(jTextField1.getText());
            int sem=Integer.parseInt(jLabel8.getText());
            String sql;
            sql="SELECT acadmic_year FROM rps.student_info WHERE reg_no='"+reg_no+"';";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            rs.next();
            String acadmic_year=rs.getString("acadmic_year");
            
            sql="SELECT * FROM subject WHERE sem='"+sem+"' AND acadmic_year='"+acadmic_year+"';";
            rs=pst.executeQuery(sql);
            
            String[] subcode=new String[10];
            int[] theory_cr=new int[10];//theory credit of subject
            int[] prac_cr=new int[10];//practical credit of subject
            int i=0;
            int count=0;
            String[] sub_name=new String[10];
            
            while(rs.next())
            {
                count=count+1;
                subcode[i]=rs.getString("sub_code");
                theory_cr[i]=rs.getInt("credit_th");
                prac_cr[i]=rs.getInt("credit_pr");
                sub_name[i]=rs.getString("sub_name");
                i=i+1;
            }
            
            
        
            
            JTextField[] midmarks={jm1,jm2,jm3,jm4,jm5,jm6,jm7,jm8};
            JTextField[] thmarks={jt1,jt2,jt3,jt4,jt5,jt6,jt7,jt8};
            JTextField[] prmarks={jp1,jp2,jp3,jp4,jp5,jp6,jp7,jp8};
            //total cedits of subject after multiplying by credits
            double total_subjectcredit=0;//sum of all practical and theory credirs
            double total_creditpoints=0;
            double gpa=0;
            
            for(int k=0;k<count;k++)
            {
                int mid=Integer.parseInt(midmarks[k].getText());
                int th=Integer.parseInt(thmarks[k].getText());
                int pr=Integer.parseInt(prmarks[k].getText());
               
                int total_marks=pr+th+mid;//total marks
                
                int back_pr=0,back_th=0;
                
                 System.out.println(subcode[i]+" "+theory_cr[i]+" "+prac_cr[i]);
                if(mid>20)
                {
                    throw new SQLException("Mid Term Marks can't be greater than 20 in "+sub_name[k]);
                }
                if(theory_cr[k]==0)
                {
                    if(total_marks<32)
                    {
                        back_pr=1;
                    }
                    if(th>80)
                    {
                        throw new SQLException("Theory Marks can't be greater than 80 in "+sub_name[k]);
                    }
                        
                }
                if(prac_cr[k]==0)
                {
                    if(total_marks<32)
                    {
                        back_th=1;
                   
                    }
                    if(pr>80)
                    {
                       throw new SQLException("Practical Marks can't be greater than 80 in "+sub_name[k]);
                    }
                    
                }
                if(theory_cr[k]!=0&&prac_cr[k]!=0)
                {
                    if((mid+th)<32)
                    {
                        back_th=1;
                    }
                    
                    if(pr<12)
                    {
                        back_pr=1;
                    }
                    
                    if(pr>30)
                    {
                       
                        throw new SQLException("Practical Marks can't be greater than 30 in "+sub_name[k]);
                    }
                    if(th>50)
                    {
                        throw new SQLException("Theory Marks can't be greater than 50 in "+sub_name[k]);
                    }
                
                }
     
                
                total_subjectcredit=total_subjectcredit+theory_cr[k]+prac_cr[k];
                double temp=total_marks;
                double gradepoints=temp/10;
                
                double temp2=theory_cr[k]+prac_cr[k];
                double credit_points=gradepoints*temp2;
                
                total_creditpoints=total_creditpoints+credit_points;
                
                
//                if(mid>20)
//                {
//                    System.out.println("tum chutiye ho");
//                }
//                if(prac_cr[i]==0)
//                {
//                    if((mid+th)>100||th>80)
//                        JOptionPane.showMessageDialog(this,"Please Enter Mrks btw 0-80");
//         
//                }
//                if(theory_cr[i]==0)
//                {
//                    if((mid+pr)>100||(pr>80))
//                        JOptionPane.showMessageDialog(this,"Please Enter Mrks btw 0-80 in '"+subcode+"'");
//                    
//                }
//                if(theory_cr[i]!=0&&prac_cr[i]!=0)
//                {
//                    if(th>50)
//                        System.out.println("No you can't do it");
//                    if(pr>30)
//                        System.out.println("this also you can't do");
//                }
         
                
                
                sql="INSERT INTO `rps`.`records` (`reg_no`, `sem`, `sub_code`, `mt_mrks`, `pr_mrks`, `th_mrks`,`gradepoint`,`credit_point`,`back_pr`,`back_th`) VALUES "
                        + "('"+reg_no+"', '"+sem+"', '"+subcode[k]+"', '"+mid+"','"+pr+"','"+th+"','"+gradepoints+"','"+credit_points+"','"+back_pr+"','"+back_th+"');";
                pst.executeUpdate(sql);
                
            
            }
     
            gpa=total_creditpoints/total_subjectcredit;        
            
            
            switch(sem)
            {
                case 1 -> sql="UPDATE `rps`.`student__records` SET `first_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 2 -> sql="UPDATE `rps`.`student__records` SET `second_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 3 -> sql="UPDATE `rps`.`student__records` SET `third_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 4 -> sql="UPDATE `rps`.`student__records` SET `fourth_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 5 -> sql="UPDATE `rps`.`student__records` SET `fifth_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 6 -> sql="UPDATE `rps`.`student__records` SET `sixth_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 7 -> sql="UPDATE `rps`.`student__records` SET `seventh_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 8 -> sql="UPDATE `rps`.`student__records` SET `eigth_sem_rollno` = '"+roll_no+"' WHERE (`reg_no` = '"+reg_no+"');";
                default -> {
                    JOptionPane.showMessageDialog(this, "Please Enter correct values");
                    return;
                }
            }
            pst.executeUpdate(sql);
            
            switch(sem)
            {
                case 1 -> sql="UPDATE `rps`.`gpa` SET `first` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 2 -> sql="UPDATE `rps`.`gpa` SET `second` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 3 -> sql="UPDATE `rps`.`gpa` SET `third` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 4 -> sql="UPDATE `rps`.`gpa` SET `fourth` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 5 -> sql="UPDATE `rps`.`gpa` SET `fifth` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 6 -> sql="UPDATE `rps`.`gpa` SET `sixth` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 7 -> sql="UPDATE `rps`.`gpa` SET `seventh` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 8 -> sql="UPDATE `rps`.`gpa` SET `eighth` = '"+gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                default -> {
                    JOptionPane.showMessageDialog(this, "Please Enter correct values");
                    return;
                }
            }
            pst.executeUpdate(sql);

            sql="SELECT * FROM rps.gpa WHERE reg_no='"+reg_no+"';";
            rs=pst.executeQuery(sql);
            double x=0;
            rs.next();
            
            x=x+rs.getDouble(3)+rs.getDouble(4)+rs.getDouble(5)+rs.getDouble(6)+rs.getDouble(7)+rs.getDouble(8)+rs.getDouble(9)+rs.getDouble(10); 
            double ogpa=x/sem;
            
            sql="UPDATE `rps`.`gpa` SET `ogpa` = '"+ogpa+"' WHERE (`reg_no` = '"+reg_no+"');";
            pst.executeUpdate(sql);
            double temp=sem+1;
            sql="UPDATE `rps`.`gpa` SET `current_sem` = '"+temp+"' WHERE (`reg_no` = '"+reg_no+"');";
            pst.executeUpdate(sql);
            if(sem<8)
            {
                sem=sem+1;
                sql="UPDATE `rps`.`student__records` SET `current_sem` = '"+sem+"' WHERE (`reg_no` = '"+reg_no+"');";
                pst.executeUpdate(sql);
            
            }
          
            rs.close();
            pst.close();
            conn.close();
            sem=sem-1;
            JOptionPane.showMessageDialog(this,reg_no+" of "+sem+" semester has been recorded");
        }
        catch (ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");      
            Statement stmt=conn.createStatement();
            String reg_no=jLabel7.getText();
            int sem=Integer.parseInt(jLabel8.getText());
            String sql="DELETE FROM `rps`.`records` WHERE (`reg_no` = '"+reg_no+"') and (`sem` = '"+sem+"');";
            stmt.executeUpdate(sql);
            conn.close();
                
            } catch (Exception x) {
                System.out.println(x.getMessage());
            }
           
        }
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm2ActionPerformed

    private void jm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fill_marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jm1;
    private javax.swing.JTextField jm2;
    private javax.swing.JTextField jm3;
    private javax.swing.JTextField jm4;
    private javax.swing.JTextField jm5;
    private javax.swing.JTextField jm6;
    private javax.swing.JTextField jm7;
    private javax.swing.JTextField jm8;
    private javax.swing.JTextField jp1;
    private javax.swing.JTextField jp2;
    private javax.swing.JTextField jp3;
    private javax.swing.JTextField jp4;
    private javax.swing.JTextField jp5;
    private javax.swing.JTextField jp6;
    private javax.swing.JTextField jp7;
    private javax.swing.JTextField jp8;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel sub2;
    private javax.swing.JLabel sub3;
    private javax.swing.JLabel sub4;
    private javax.swing.JLabel sub5;
    private javax.swing.JLabel sub6;
    private javax.swing.JLabel sub7;
    private javax.swing.JLabel sub8;
    // End of variables declaration//GEN-END:variables
}
