/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication12;

/**
 *
 * @author rohit
 */
import java.io.StringWriter;
import java.sql.*;
import javax.print.DocFlavor;
import javax.swing.*;
public class update_records extends javax.swing.JFrame {

    /**
     * Creates new form update_records
     */
    public update_records() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enrollment Number");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Semester");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("UPDATE RECORDS");

        jLabel4.setText("Subject ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Theory");

        jLabel6.setText("Practical");

        jLabel7.setText("MidTerm");

        jButton4.setText("Update Marks");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(326, 326, 326)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1)
                        .addGap(121, 121, 121)
                        .addComponent(jButton4)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
                Object selected=jComboBox1.getSelectedItem();
//                System.out.println("Selected Item  = " + selected);
                
                
                String sname=String.valueOf(selected);
                
                if(selected==null)
                {
                    return;
                }
        String reg_no=jTextField1.getText();
        int sem=Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");
            Statement stmt=conn.createStatement();
            String sql;
            sql="SELECT sub_code,credit_th,credit_pr FROM rps.subject WHERE sub_name='"+sname+"';";
            ResultSet rst=stmt.executeQuery(sql);
            rst.next();
            String sub_code=rst.getString("sub_code");
            int sum_sub_credit=rst.getInt("credit_th")+rst.getInt("credit_pr");
            sql="SELECT pr_mrks,th_mrks,mt_mrks FROM rps.records WHERE reg_no='"+reg_no+"' AND sub_code='"+sub_code+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            int th_mrk=rst.getInt("th_mrks");
            int pr_mrk=rst.getInt("pr_mrks");
            int mt_mrk=rst.getInt("mt_mrks");
            jTextField3.setText(Integer.toString(th_mrk));
            jTextField4.setText(Integer.toString(pr_mrk));
            jTextField5.setText(Integer.toString(mt_mrk));
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
                
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String sname=String.valueOf(jComboBox1.getSelectedItem());
        String reg_no=jTextField1.getText();
        int sem=Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");
            Statement stmt=conn.createStatement();
            String sql;
            sql="SELECT acadmic_year FROM rps.student_info WHERE reg_no='"+reg_no+"';";
            ResultSet rst=stmt.executeQuery(sql);
            rst.next();
            String acadmic_year=rst.getString("acadmic_year");
            sql="SELECT sub_code,credit_th,credit_pr FROM rps.subject WHERE sub_name='"+sname+"' AND acadmic_year='"+acadmic_year+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            int sum_sub_credit=rst.getInt("credit_th")+rst.getInt("credit_pr");
            String sub_code=rst.getString("sub_code");
            sql="SELECT pr_mrks,th_mrks,mt_mrks FROM rps.records WHERE reg_no='"+reg_no+"' AND sub_code='"+sub_code+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            
            int th_mrk=Integer.valueOf(jTextField3.getText());
            int mt_mrk=Integer.valueOf(jTextField5.getText());
            int pr_mrk=Integer.valueOf(jTextField4.getText());
            double gradepoint=(th_mrk+mt_mrk+pr_mrk)/10;
            double creditpoint=gradepoint*sum_sub_credit;
            sql="UPDATE `rps`.`records` SET `mt_mrks` = '"+mt_mrk+"', `pr_mrks` = '"+pr_mrk+"', `th_mrks` = '"+th_mrk+"', `gradepoint` = '"+gradepoint+"', `credit_point` = '"+creditpoint+"' WHERE (`reg_no` = '"+reg_no+"') and (`sub_code` = '"+sub_code+"');";
            stmt.executeUpdate(sql);
            sql="SELECT SUM(credit_point) FROM records WHERE reg_no='"+reg_no+"' AND sem='"+sem+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            int sum_credit=rst.getInt(1);
            System.out.println(sum_credit+"totalcredit"+sum_sub_credit);
            
            sql="SELECT SUM(credit_pr),SUM(credit_th) FROM subject WHERE sem='"+sem+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            int total_credir=rst.getInt(1)+rst.getInt(2);
//            System.out.println("total subject credit:"+total_credir);
            
            int new_gpa=sum_credit/total_credir;
            
            switch(sem)
            {
                case 1 -> sql="UPDATE `rps`.`gpa` SET `first` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 2 -> sql="UPDATE `rps`.`gpa` SET `second` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 3 -> sql="UPDATE `rps`.`gpa` SET `third` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 4 -> sql="UPDATE `rps`.`gpa` SET `fourth` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 5 -> sql="UPDATE `rps`.`gpa` SET `fifth` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 6 -> sql="UPDATE `rps`.`gpa` SET `sixth` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 7 -> sql="UPDATE `rps`.`gpa` SET `seventh` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                case 8 -> sql="UPDATE `rps`.`gpa` SET `eighth` = '"+new_gpa+"' WHERE (`reg_no` = '"+reg_no+"');";
                default -> {
                    JOptionPane.showMessageDialog(this, "Please Enter correct values");
                    return;
                }
            }
            
            stmt.executeUpdate(sql);
            
            
            sql="SELECT * FROM rps.gpa WHERE reg_no='"+reg_no+"';";
            rst=stmt.executeQuery(sql);
            double x=0;
            rst.next();
            
            x=x+rst.getDouble(3)+rst.getDouble(4)+rst.getDouble(5)+rst.getDouble(6)+rst.getDouble(7)+rst.getDouble(8)+rst.getDouble(9)+rst.getDouble(10); 
            sql="SELECT current_sem FROM rps.gpa WHERE reg_no='"+reg_no+"';";
            rst=stmt.executeQuery(sql);
            rst.next();
            sem=rst.getInt("current_sem");
            System.out.println(sem);
            if(sem<8)
               sem=sem-1;
            
            double ogpa=x/sem;


            sql="UPDATE `rps`.`gpa` SET `ogpa` = '"+ogpa+"' WHERE (`reg_no` = '"+reg_no+"');";
            stmt.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(this,"Marks of "+reg_no+" of "+sem+" of "+String.valueOf(jComboBox1.getSelectedItem())+" has been updated");
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
         String reg_no=jTextField1.getText();
        int sem=Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/rps","root","ro07hi11t99");
            Statement stmt=conn.createStatement();
            String sql;
            sql="SELECT acadmic_year FROM rps.student_info WHERE reg_no='"+reg_no+"';";
            ResultSet rst=stmt.executeQuery(sql);
            rst.next();
            String acadmic_year=rst.getString("acadmic_year");
            sql="SELECT name FROM rps.student_info WHERE reg_no='"+reg_no+"';";
            rst=stmt.executeQuery(sql);
            
            if(jComboBox1.getItemCount()>0)
             {
                        jComboBox1.removeAllItems();
             }
            if(rst.next())
            {
                sql="SELECT * FROM rps.subject WHERE sem='"+sem+"' AND acadmic_year='"+acadmic_year+"';";
                rst=stmt.executeQuery(sql);
                String[] sub_code=new String[10];
                String[] sub_name=new String[10];
                int i=0;
                while(rst.next())
                {
                    sub_code[i]=rst.getString("sub_code");
                    sub_name[i]=rst.getString("sub_name");
//                    System.out.println(sub_code[i]+sub_name[i]);
                    jComboBox1.addItem(sub_name[i]);
                    i=i+1;
                } 
            }
            else
               JOptionPane.showMessageDialog(this, "Invalid Enrollment Number");
            
                
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       Mainframe m=new Mainframe();
       m.setVisible(true);
       this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
